import type { Config } from "tailwindcss";

// 색상 토큰은 Stitch에서 생성한 "동네한끼 기본 테마" 디자인 시스템 값을 그대로 옮긴 것.
// (Material 3 스타일 named colors, primary custom color #E8664B 기반)
const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#6d3529",
        error: "#a8364b",
        "primary-fixed-dim": "#eea08f",
        "secondary-fixed": "#ffdad3",
        "on-secondary-container": "#694a44",
        "surface-container-high": "#fae3df",
        "primary-container": "#fdad9c",
        primary: "#8c4e41",
        "surface-container-highest": "#f6ddd8",
        "on-error": "#fff7f7",
        secondary: "#785750",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#6e511e",
        "on-tertiary": "#fff8f2",
        "tertiary-dim": "#6b4e1b",
        "secondary-dim": "#6b4b45",
        surface: "#fff8f6",
        "surface-container": "#ffe9e5",
        "on-secondary-fixed": "#553832",
        "primary-fixed": "#fdad9c",
        outline: "#8a7672",
        "on-secondary-fixed-variant": "#74544d",
        "on-surface": "#3e2f2c",
        "on-surface-variant": "#6d5b57",
        "outline-variant": "#c3ada8",
        background: "#fff8f6",
        "on-primary-container": "#622d21",
        "secondary-fixed-dim": "#f6cbc2",
        "on-primary-fixed": "#48190f",
        "on-primary": "#fff7f6",
        "on-tertiary-container": "#644815",
        "surface-tint": "#8c4e41",
        "on-background": "#3e2f2c",
        "tertiary-fixed-dim": "#eec687",
        "error-dim": "#6b0221",
        "error-container": "#f97386",
        tertiary: "#785a26",
        "tertiary-fixed": "#fdd494",
        "inverse-primary": "#fdad9c",
        "surface-dim": "#edd5d0",
        "surface-variant": "#f6ddd8",
        "primary-dim": "#7e4336",
        "inverse-surface": "#130d0b",
        "surface-container-low": "#fff0ee",
        "inverse-on-surface": "#a79a97",
        "secondary-container": "#ffdad3",
        "on-tertiary-fixed": "#4e3503",
        "on-secondary": "#fff7f6",
        "on-error-container": "#6e0523",
        "tertiary-container": "#fdd494",
        "surface-bright": "#fff8f6",
        // 브랜드 포인트 컬러 (카테고리 칩/뱃지 강조 전용, 디자인 원칙상 제한적으로만 사용)
        accent: "#E8664B",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["var(--font-inter)", "sans-serif"],
        display: ["var(--font-inter)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        label: ["var(--font-public-sans)", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
